/* Action Types */
export const ACTION_TEST = 'App/ACTION_TEST';
export const ACTION_SHOW_LOADING = 'App/ACTION_SHOW_LOADING';
export const ACTION_HIDE_LOADING = 'App/ACTION_HIDE_LOADING';
export const ACTION_SHOW_ERROR = 'App/ACTION_SHOW_ERROR';
export const ACTION_GOTO_CHAT = 'App/ACTION_GOTO_CHAT';
export const ACTION_SEARCH_REQUEST = 'App/ACTION_SEARCH_REQUEST';

